# Generated by Django 5.2.3 on 2025-06-19 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('phone', 'serialNumber', 'cuid', 'ticketNumber')},
        ),
    ]
