# Generated by Django 5.2.3 on 2025-06-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('round_1', 'Round 1'), ('round_2', 'Round 2'), ('round_3', 'Round 3'), ('round_4', 'Round 4'), ('completed', 'Completed'), ('not started', 'Not started'), ('1', 'Round 1'), ('2', 'Round 2'), ('3', 'Round 3'), ('4', 'Round 4')], default='not_started', max_length=20),
        ),
    ]
