# Generated by Django 5.2.3 on 2025-06-20 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_add_question_round'),
        ('interviews', '0002_interviewround_interview_interview_round'),
    ]

    operations = [
    ]
