# Generated by Django 5.2.3 on 2025-06-26 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_add_form_data_field'),
        ('interviews', '0003_merge_20250620_0438'),
    ]

    operations = [
    ]
